baseURL = "https://rawand.dev/"

# set your your own ga token here.
#googleAnalytics = ""

languageCode = "en-us"

# for using avicenna you need to set the `themes` to 'avicenna'
theme = "avicenna"

# This is your page title, it appears in your tab
title = "Rawand Farhad - Software Engineer"

[params]
# it is used for the copy-right section of your page
name = "Rawand Farhad"
